
data_folder: "/home/roblab20/tactile_diffusion/datastore_real" # where is all your data, can include * for globbing
output_dir: "/home/roblab20/tactile_diffusion/datastore_real" # where to save checkpoints and logs
gpu: 0

# Train params for on screen logging
save_freq: 100
eval_freq: 10
print_freq: 100

# load student checkpoint
eval: False
load_path: '' #/home/roblab20/osher3_workspace/src/isaacgym/python/IsaacGymInsertion/isaacgyminsertion/outputs/diff/'
eval_path: '' #/home/roblab20/tactile_diffusion/datastore_real/2/2024-06-14_14-56-47/obs/obs.npz'
# basic training hyperparameters
cond_on_grasp: True
model_save_path: ''

epochs: 50
obs_horizon: 4
action_horizon: 8
pred_horizon: 16
num_diffusion_iters: 100

batch_size: 16
learning_rate: 5e-4
train_test_split: 0.9

representation_type: ["eef_pos","tactile"]

# normalize data
normalize_keys: ["eef_pos", "action", "arm_joints"]
normalize_file: "/home/roblab20/tactile_diffusion/datastore_real/normalization.pkl"



img_color_jitter: False
img_gaussian_noise: 0.0
img_masking_prob: 0.0
img_patch_size: 16
img_dropout_rate: 0.0  # For the image encoder of Diffusion Policy

tactile_width: 64
tactile_height: 64
tactile_color_jitter: False
tactile_gaussian_noise: 0.0
tactile_masking_prob: 0.0
tactile_patch_size: 16
tactile_dropout_rate: 0.0  # For the image encoder of Diffusion Policy

pcl_dropout_rate: 0.0

predict_eef_delta: False
clip_far: False
predict_pos_delta: False
use_ddim: False

policy_dropout_rate: 0.0
dropout_rate: 0.0  # For the state encoder of Diffusion Policy
weight_decay: 1e-5

state_noise: 0.0

num_workers: 12

eef_pos_output_size: 64
hand_joints_output_size: 64
arm_joints_output_size: 64
image_output_size: 64
tactile_output_size: 64
pcl_output_size: 64

without_sampling: False

compile_train: False

identity_encoder: False

# wandb logging
wandb_entity_name: None
wandb_exp_name: None
use_wandb: False
wandb_project_name: "tactile_diffusion"