
data_folder: "/home/roblab20/tactile_diffusion/datastore_real" # where is all your data, can include * for globbing
output_dir: "/home/roblab20/tactile_diffusion/datastore_real" # where to save checkpoints and logs
gpu: 0

# Train params for on screen logging
eval: False
save_freq: 100
eval_freq: 10
print_freq: 100

# load student checkpoint
model_save_path: ''
load_path: ''

# basic training hyperparameters
cond_on_grasp: False

epochs: 100
obs_horizon: 1
action_horizon: 6
pred_horizon: 16
num_diffusion_iters: 100

batch_size: 8
learning_rate: 5e-4
train_test_split: 0.9

representation_type: "eef_pos-tactile"

# normalize data
normalize_keys: ["eef_pos", "action", "arm_joints"]
normalize_file: "/home/roblab20/tactile_diffusion/datastore_real/normalization.pkl"


img_color_jitter: False
img_gaussian_noise: 0.0
img_masking_prob: 0.0
img_patch_size: 16
img_dropout_rate: 0.0  # For the image encoder of Diffusion Policy

tactile_color_jitter: False
tactile_gaussian_noise: 0.0
tactile_masking_prob: 0.0
tactile_patch_size: 16
tactile_dropout_rate: 0.0  # For the image encoder of Diffusion Policy

predict_eef_delta: False
clip_far: False
predict_pos_delta: False
use_ddim: False

policy_dropout_rate: 0.0
dropout_rate: 0.0  # For the state encoder of Diffusion Policy
weight_decay: 1e-5

state_noise: 0.0

num_workers: 8

eef_pos_output_size: 64
hand_joints_output_size: 64
arm_joints_output_size: 64
image_output_size: 64
tactile_output_size: 64

without_sampling: False

compile_train: False

identity_encoder: False

# wandb logging
wandb_entity_name: None
wandb_exp_name: None
use_wandb: False
wandb_project_name: "tactile_diffusion"

external_cam:
  external_cam: False
  cam_res:
    w: 320
    h: 180
  cam_type: 'depth'
  save_im: False
  far_clip: 1.0
  near_clip: 0.0
  dis_noise: 0.001