seed: 42 # not sure if this is used yet.
data_folder: "/home/roblab20/tactile_insertion/datastore_42_contact2" # where is all your data, can include * for globbing
output_dir: "/home/roblab20/tactile_insertion/datastore_42_contact2" # where to save checkpoints and logs

# supervised learning
train:
  # basic training hyperparameters
  epochs: 100
  train_batch_size: 16
  val_batch_size: 16
  learning_rate: 5e-4
  train_test_split: 0.98
  action_regularization: False # propagate gradients for action loss
  action_regularization_weight: 0.0 # weight for action regularization

  scheduler: "cosine"
  warmup: False
  warmup_epochs: 4
  cyclic_period: 10
  plateau_patience: 3
  plateau_factor: 0.5

  # loss scaling
  latent_scale: 1.0
  action_scale: 1.0

  # Train params for on screen logging
  print_every: 100
  eval_every: 4000
  test_every: 10000
  test_episodes: 2 # per epoch batch

  # Only val/test ( val- dataset, test - env)
  only_test: False
  only_validate: False

  # normalize data
  normalize_keys: ["eef_pos", "action", "hand_joints", "plug_pos_error", "plug_quat_error", "plug_hand_quat", "plug_hand_pos"]

  normalize_file: "/home/roblab20/tactile_insertion/datastore_42_contact2/normalization.pkl"

  # load student checkpoint
  load_checkpoint: False
  student_ckpt_path: "/home/roblab20/tactile_insertion/datastore_0_contact2/tac+eef/checkpoints/model_2.pt"

# model configuration
model:
  # linear embedding
  linear:
    input_size: 6
    # TODO: add model layers here

  # tactile embedding
  cnn:
    in_channels: 3
    # TODO: add model layers here

  # tactile+obs encoder
  transformer:
    full_sequence: False # if True, it makes sequence length 500
    sequence_length: 1 # ${...task.rl.max_episode_length}
    num_layers: 4
    num_heads: 4
    dim_factor: 4
    output_size: 8
    tactile_encoding_size: 128
    img_encoding_size: 128

# wandb logging
wandb:
  wandb_enabled: False
  wandb_project_name: "tactile_insertion"


