seed: 42 # not sure if this is used yet.
data_folder: "/common/users/dm1487/inhand_manipulation_data_store/datastore_44" # where is all your data, can include * for globbing
output_dir: "/common/users/dm1487/isaacgym_new/python/IsaacGymInsertion/isaacgyminsertion/outputs/offline_student_test" # where to save checkpoints and logs

# supervised learning
train:
  # basic training hyperparameters
  epochs: 20
  train_batch_size: 1
  val_batch_size: 8
  learning_rate: 0.001
  train_test_split: 0.99
  action_regularization: False # propogate gradients for action loss
  action_regularization_weight: 0.0 # weight for action regularization

  # loss scaling
  latent_scale: 1.0
  action_scale: 1.0

  # Train params for on screen logging
  print_every: 50
  eval_every: 250
  test_every: 50
  test_episodes: 2 # per epoch batch

  # Only val/test ( val- dataset, test - env)
  only_test: False
  only_validate: False

  # normalize data
  normalize_keys: ["arm_joints", "eef_pos", "noisy_socket_pos", "target"]
  normalize_file: "/common/users/dm1487/isaacgym_new/python/IsaacGymInsertion/algo/models/transformer/normalization.pkl"

  # load checkpoint
  load_checkpoint: False
  ckpt_path: "/common/users/dm1487/isaacgym_new/python/IsaacGymInsertion/isaacgyminsertion/outputs/offline_student/2023-11-01_11-37-16/checkpoints/model_4.pt"

# model configuration
model:
  # linear embedding
  linear:
    input_size: 33
    # TODO: add model layers here

  # tactile embedding
  cnn:
    in_channels: 1
    out_channels: 1 # 32
    kernel_size: 3
    # TODO: add model layers here

  # tactile+obs encoder
  transformer:
    full_sequence: False # if True, it makes sequence length 500
    sequence_length: 100 # ${...task.rl.max_episode_length}
    embed_size: 32
    hidden_size: 64
    num_layers: 2
    num_heads: 2
    output_size: 8
  
# wandb logging
wandb:
  wandb_enabled: False
  wandb_project_name: "tactile_insertion"


