seed: 42 # not sure if this is used yet.
data_folder: "/common/users/dm1487/inhand_manipulation_data_store/datastore_30*" # where is all your data, can include * for globbing
output_dir: "/common/users/dm1487/isaacgym_new/python/IsaacGymInsertion/isaacgyminsertion/outputs/offline_student" # where to save checkpoints and logs

# supervised learning
train:
  # basic training hyperparameters
  epochs: 40
  train_batch_size: 16
  val_batch_size: 32
  learning_rate: 0.001
  train_test_split: 0.95
  action_regularization: True # propogate gradients for action loss

  # for on screen logging
  print_every: 50
  eval_every: 250
  test_every: 50

# model configuration
model:
  # linear embedding
  linear: 
    input_size: 33
    # TODO: add model layers here

  # tactile embedding
  cnn:
    in_channels: 9
    out_channels: 32
    kernel_size: 5
    # TODO: add model layers here

  # tactile+obs encoder
  transformer:
    sequence_length: ${...task.rl.max_episode_length}
    embed_size: 256
    hidden_size: 512
    num_layers: 2
    num_heads: 2
    output_size: 8
  
# wandb logging
wandb:
  wandb_enabled: True
  wandb_project_name: "tactile_insertion"


