seed: 42 # not sure if this is used yet.
data_folder: "/common/users/dm1487/inhand_manipulation_data_store/datastore_41" # where is all your data, can include * for globbing
output_dir: "/common/users/dm1487/isaacgym_new/python/IsaacGymInsertion/isaacgyminsertion/outputs/offline_student" # where to save checkpoints and logs

# supervised learning
train:
  # basic training hyperparameters
  epochs: 40
  train_batch_size: 2
  val_batch_size: 32
  learning_rate: 0.0005
  train_test_split: 0.98
  action_regularization: False # propogate gradients for action loss

  # for on screen logging
  print_every: 50
  eval_every: 1000
  test_every: 250
  test_episodes: 5
  
# model configuration
model:
  # linear embedding
  linear: 
    input_size: 43
    # TODO: add model layers here

  # tactile embedding
  cnn:
    in_channels: 9
    out_channels: 1 # 32
    kernel_size: 3
    # TODO: add model layers here

  # tactile+obs encoder
  transformer:
    full_sequence: False # if True, it makes sequence length 500
    sequence_length: 100 # ${...task.rl.max_episode_length}
    embed_size: 32
    hidden_size: 64
    num_layers: 2
    num_heads: 2
    output_size: 4
  
# wandb logging
wandb:
  wandb_enabled: False
  wandb_project_name: "tactile_insertion"


