seed: 0 # not sure if this is used yet.
data_folder: "/home/roblab20/tactile_tests/datastore_real" # where is all your data, can include * for globbing
output_dir: "/home/roblab20/tactile_tests/datastore_real" # where to save checkpoints and logs

only_bc: True
multi_gpu: False
from_offline: False
gpu_ids: [0, 1]
img_type: "depth"
img_color_jitter: False
img_width: 54 # 54
img_height: 96 # 96
img_gaussian_noise: 0.00
img_masking_prob: 0.0 # 0.3
img_patch_size: 16
img_crop_w: 0
img_crop_h: 0

tactile_type: 'gray'
tactile_gaussian_noise: 0.001
tactile_masking_prob: 0.0
tactile_patch_size: 16
tactile_color_jitter: False
tactile_width: 32
tactile_height: 64
tactile_crop_w: 0 #4
tactile_crop_h: 0 #8

# supervised learning
train:
  # basic training hyperparameters
  epochs: 100
  train_batch_size: 64
  val_batch_size: 64
  learning_rate: 1e-4
  train_test_split: 0.98
  action_regularization: False # propagate gradients for action loss
  action_regularization_weight: 0.0 # weight for action regularization

  scheduler: "cosine"
  warmup: False
  warmup_epochs: 4
  cyclic_period: 10
  plateau_patience: 3
  plateau_factor: 0.5

  # loss scaling
  latent_scale: 1.0
  action_scale: 1.0

  # Train params for on screen logging
  print_every: 1000
  eval_every: 1000
  test_every: 2000
  test_episodes: 4000 # per epoch batch

  # Only val/test ( val- dataset, test - env)
  only_test: False
  only_validate: False

  obs_keys: ["eef_pos", "action", "latent", "obs_hist", "noisy_socket_pos", "socket_pos",
             "hand_joints", "plug_hand_quat", "plug_hand_pos", "plug_pos_error", "plug_quat_error"]

  normalize_obs_keys: ["eef_pos",
                       "noisy_socket_pos",
                       "action",
                       "plug_hand_quat",
                       "plug_hand_pos",
                       "socket_pos"
#                       "plug_pos_error",
#                       "plug_quat_error"
  ]
  load_stats: False
  normalize_file: "/home/roblab20/osher3_workspace/src/isaacgym/python/IsaacGymInsertion/isaacgyminsertion/outputs/gt_test/student/normalization.pkl"

  # load student checkpoint
  load_checkpoint: False
  student_ckpt_path: "/home/roblab20/tactile_insertion/datastore_0_contact2/tac+eef/checkpoints/model_2.pt"

# model configuration
model:
  # linear embedding
  linear:
    input_size: 15

  use_img: True
  use_seg: True
  use_pcl: False
  use_tactile: False
  use_lin: True

  model_type: 'tact'

  transformer:
    sequence_length: 1
    num_layers: 2
    num_heads: 2
    dim_factor: 4
    output_size: 8
    tactile_encoding_size: 32
    img_encoding_size: 32
    seg_encoding_size: 32
    lin_encoding_size: 32
    load_tact: False
    tact_path: "/home/roblab20/osher3_workspace/src/isaacgym/python/IsaacGymInsertion/isaacgyminsertion/outputs/gt_test/tact/checkpoints/model_last.pt"

  tact:
    sequence_length: 1 # ${...task.rl.max_episode_length}
    num_layers: 4
    num_heads: 4
    dim_factor: 4
    output_size: 6
    tactile_encoding_size: 64
    img_encoding_size: 64
    use_img: False
    use_tactile: False
    use_lin: True
# wandb logging
wandb:
  wandb_enabled: False
  wandb_project_name: "tactile_insertion"


