seed: ${..seed}
algo: PPO # ExtrinsicAdapt, PPO
load_path: ${..checkpoint} # path to the checkpoint to load

network:
  mlp:
    units: [512, 256, 128]
  priv_mlp:
    units: [256, 128, 8]
  contact_mlp:
    units: [ 128, 64, 8]

  tactile_encoder:
    num_channels: ${....task.tactile.encoder.num_channels}
    tactile_seq_length: ${....task.env.tactile_history_len}
    img_width: ${....task.tactile.encoder.width}
    img_height: ${....task.tactile.encoder.height}

ppo:
  output_name: 'debug'
  multi_gpu: ${...multi_gpu}
  normalize_input: True
  normalize_value: True
  value_bootstrap: True # for "value" based bootstrap, no connection to GAE (logically we may be seeing reduced variance during training)
  shared_parameters: False # shared params for actor and critic
  num_actors: ${...task.env.numEnvs}
  normalize_advantage: True
  gamma: 0.99
  tau: 0.95
  learning_rate: 0.00025
  kl_threshold: 0.02
  # PPO batch collection
  horizon_length: 64 # 64 , 8
  mini_epochs: 8 # 8
  minibatch_size: 24 # batch size = num_envs * horizon_length; minibatch_size = batch_size / num_minibatches

  # PPO loss setting
  clip_value: True
  critic_coef: 4
  entropy_coef: 0.0
  e_clip: 0.2
  bounds_loss_coef: 0.0001
  # grad clipping
  truncate_grads: True # False
  grad_norm: 1
  # snapshot setting
  save_best_after: 1000000
  save_frequency: 100
  max_agent_steps: 1500000000

  # rma setting
  priv_info: True
  tactile_info: False
  img_info: False
  pcl_info: False
  seg_info: False
  obs_info: False
  only_contact: False
  split_latent: False

  ft_seq_length: ${...task.env.ft_history_len}
  obs_seq_length: ${...task.env.numObsHist}
  priv_info_dim: ${...task.env.numStates}
  compute_contact_gt: ${...task.env.compute_contact_gt}

  num_points: ${...task.env.num_points}
  sim2real: ${...task.tactile.sim2real}

  student_obs_input_shape: ${...task.env.numObsStudent}
  save_buffer: False
  ft_input_dim: 6